stages:
  - stage: Build
    displayName: "Build"
    jobs:
      - job: PublishTerraformArtifact
        workspace:
          clean: all
        displayName: "Publish Terraform Artifact"
        steps:
          - task: PublishBuildArtifacts@1
            displayName: "Publish Terraform Artifact"
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/pipeline/terraform/prerequisites'
              ArtifactName: TerraformArtifact